# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/proto_test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/proto_test.proto',
  package='proto_test',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x17protos/proto_test.proto\x12\nproto_test\"/\n\tProtoTest\x12\x11\n\x03num\x18\x01 \x02(\x05:\x04\x31\x30\x30\x30\x12\x0f\n\x04\x66num\x18\x02 \x02(\x02:\x01\x31')
)




_PROTOTEST = _descriptor.Descriptor(
  name='ProtoTest',
  full_name='proto_test.ProtoTest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='proto_test.ProtoTest.num', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=1000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fnum', full_name='proto_test.ProtoTest.fnum', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['ProtoTest'] = _PROTOTEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoTest = _reflection.GeneratedProtocolMessageType('ProtoTest', (_message.Message,), dict(
  DESCRIPTOR = _PROTOTEST,
  __module__ = 'protos.proto_test_pb2'
  # @@protoc_insertion_point(class_scope:proto_test.ProtoTest)
  ))
_sym_db.RegisterMessage(ProtoTest)


# @@protoc_insertion_point(module_scope)
